import type { NoticeRecord, NoticeSearchCriteria } from "./notices.types"

export const initialNoticeCriteria: NoticeSearchCriteria = {
  title: "",
  author: "",
  content: "",
  startDate: "2026-01-01",
  endDate: "2026-08-12",
}

// TODO: 운영 API 연결 후 fixture를 실제 알림글 응답으로 교체합니다.
export const noticeRecords: readonly NoticeRecord[] = [
  {
    number: 17,
    title: "수영구 세입·세출예산 운영정보공개시스템 이용 안내",
    author: "관리자",
    createdDate: "2026-08-11",
    content: "자금운용, 세입 및 세출정보 조회 방법을 안내합니다.",
    attachmentName: "시스템_이용안내.pdf",
  },
  {
    number: 16,
    title: "2026년 제2회 추가경정예산 공개 안내",
    author: "기획전략과",
    createdDate: "2026-08-04",
    content: "2026년 제2회 추가경정예산 자료가 공개되었습니다.",
    attachmentName: "2026년_제2회_추경예산.pdf",
  },
  {
    number: 15,
    title: "세입·세출 현황 데이터 갱신 안내",
    author: "재무과",
    createdDate: "2026-07-28",
    content: "세입·세출 현황 데이터 갱신 주기와 기준 시점을 알려드립니다.",
  },
  {
    number: 14,
    title: "시스템 정기 점검에 따른 서비스 일시 중단 안내",
    author: "관리자",
    createdDate: "2026-07-17",
    content: "안정적인 서비스 제공을 위한 정기 점검이 진행됩니다.",
  },
  {
    number: 13,
    title: "2026년 지방재정공시 자료 안내",
    author: "기획전략과",
    createdDate: "2026-07-02",
    content: "2026년 지방재정공시 자료와 확인 경로를 안내합니다.",
    attachmentName: "2026년_지방재정공시.pdf",
  },
  {
    number: 12,
    title: "상반기 자금운용현황 공개 일정 안내",
    author: "재무과",
    createdDate: "2026-06-19",
    content: "2026년 상반기 자금운용현황 공개 일정을 알려드립니다.",
  },
  {
    number: 11,
    title: "예산집행현황 조회 항목 변경 안내",
    author: "기획전략과",
    createdDate: "2026-06-08",
    content: "예산집행현황 표의 조회 항목과 표시 기준이 변경되었습니다.",
  },
  {
    number: 10,
    title: "공개자료 다운로드 기능 개선 안내",
    author: "관리자",
    createdDate: "2026-05-26",
    content: "목록별 공개자료 다운로드 기능이 개선되었습니다.",
  },
  {
    number: 9,
    title: "사업별 세부설명 자료 정비 안내",
    author: "기획전략과",
    createdDate: "2026-05-12",
    content: "사업별 세부설명 자료의 표기 방식과 분류 체계를 정비했습니다.",
  },
  {
    number: 8,
    title: "2025 회계연도 결산정보 공개",
    author: "재무과",
    createdDate: "2026-04-30",
    content: "2025 회계연도 결산정보를 공개합니다.",
    attachmentName: "2025회계연도_결산정보.pdf",
  },
  {
    number: 7,
    title: "개인정보 보호를 위한 이용자 유의사항",
    author: "관리자",
    createdDate: "2026-04-15",
    content: "공개시스템 이용 시 개인정보 보호를 위한 유의사항입니다.",
  },
  {
    number: 6,
    title: "세출현황 통계목 분류 기준 안내",
    author: "재무과",
    createdDate: "2026-03-27",
    content: "세출현황에서 사용하는 통계목 분류 기준을 안내합니다.",
    attachmentName: "통계목_분류기준.xlsx",
  },
  {
    number: 5,
    title: "모바일 화면 이용 환경 개선 안내",
    author: "관리자",
    createdDate: "2026-03-16",
    content: "모바일 기기에서의 검색 및 표 조회 환경을 개선했습니다.",
  },
  {
    number: 4,
    title: "2026년도 본예산 공개 안내",
    author: "기획전략과",
    createdDate: "2026-02-27",
    content: "2026년도 본예산 자료를 공개합니다.",
    attachmentName: "2026년도_본예산.pdf",
  },
  {
    number: 3,
    title: "서비스 이용약관 개정 안내",
    author: "관리자",
    createdDate: "2026-02-10",
    content: "운영정보공개시스템 서비스 이용약관이 일부 개정됩니다.",
  },
  {
    number: 2,
    title: "공개시스템 데이터 기준일 안내",
    author: "재무과",
    createdDate: "2026-01-21",
    content: "조회 화면별 데이터 기준일과 갱신 시점을 안내합니다.",
  },
  {
    number: 1,
    title: "수영구 세입·세출예산 운영정보공개시스템 개편 안내",
    author: "관리자",
    createdDate: "2026-01-05",
    content: "더 편리한 정보 조회를 위해 공개시스템 화면을 개편했습니다.",
    attachmentName: "공개시스템_개편안내.pdf",
  },
]
